baseURL = "https://tricitiesitsupport.ca/"
locale = 'en-us'
title = 'My New Hugo Project'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
disableKinds = ["taxonomy", "term"]
