baseURL = "https://tricitiesitsupport.ca/"
locale = 'en-us'
title = "Tri-Cities IT Support"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
disableKinds = ["taxonomy", "term"]
